### ISSUE TITLE
Failing to display "htop" output properly

### ISSUE THREAD

**Issue by pavlovnicola** [jacektrocinski/pretty-putty#4]
Hi,

I would like to use the dark color scheme but it has issues when running the linux application "htop".

It is not showing the values/percentages correctly (the values for CPUs, Mem and Swp).

**Comment by jacektrocinski** [comment]
Please send a screenshot of the terminal with Pretty PuTTY applied versus without it.

Here's my terminal with Pretty PuTTY dark:

![htop_pretty_putty](https://user-images.githubusercontent.com/19655197/159443492-0b4d4a06-53db-4886-8186-5ea28987b680.png)

_Hint: You can drag and drop an image into a GitHub comment to post an image._

**Comment by pavlovnicola** [comment]
Hi,

Here are the images:

![image](https://user-images.githubusercontent.com/20930386/159444741-87b68278-6996-4704-9333-8bfac3e6f220.png)

![image](https://user-images.githubusercontent.com/20930386/159444804-12adcb6a-c714-4e91-bd29-8d3bfce3e85b.png)

Thank you.

**Comment by jacektrocinski** [comment]
@pavlovnicola Try doing the following in `htop`: 

_Press F2 -> Colors -> Choose "Broken Grey"_

`htop` should now display as follows:

![Screenshot 2022-03-22 183044](https://user-images.githubusercontent.com/19655197/159540636-21cde51f-4621-4e7b-b129-467638e82f42.png)

**Comment by jacektrocinski** [comment]
Happy to help, closing this issue.
